# Generated by Django 4.2.7 on 2025-06-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='availability',
            field=models.CharField(blank=True, help_text='e.g., Mon - Fri: 9AM - 6PM PST', max_length=200),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
