# Generated by Django 4.2.7 on 2025-06-26 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Review & Recommendation', 'verbose_name_plural': 'Reviews & Recommendations'},
        ),
    ]
