# Generated by Django 4.2.7 on 2025-06-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_testimonial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='profile_image',
            field=models.CharField(blank=True, help_text='Profile image URL or path', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, help_text='Image URL or path', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.CharField(blank=True, help_text='Photo URL or path', max_length=500, null=True),
        ),
    ]
